version: '3'
services:
  neo4j:
      image: neo4j:latest
      container_name: neo4j_amundsen
      environment:
        - NEO4J_AUTH=neo4j/longertest
      ulimits:
        nofile:
          soft: 40000
          hard: 40000
      ports:
          - 7474:7474
          - 7687:7687
      volumes:
          - ./example/docker/neo4j/conf:/var/lib/neo4j/conf
          - ./.local/neo4j/data:/data
      networks:
        - amundsennet
  elasticsearch:
      image: elasticsearch:8.0.0
      container_name: es_amundsen
      ports:
          - 9200:9200
      networks:
        - amundsennet
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
  amundsensearch:
      build:
        context: .
        dockerfile: Dockerfile.search.public
      container_name: amundsensearch
      ports:
        - 5001:5001
      depends_on:
        - elasticsearch
      networks:
        - amundsennet
      environment:
        - PROXY_ENDPOINT=es_amundsen
  amundsenmetadata:
      build:
        context: .
        dockerfile: Dockerfile.metadata.public
      container_name: amundsenmetadata
      depends_on:
        - neo4j
      ports:
        - 5002:5002
      networks:
        - amundsennet
      environment:
         - PROXY_HOST=bolt://neo4j_amundsen
         - PROXY_ENCRYPTED=False
  amundsenfrontend:
      build:
        args:
          SEARCHSERVICE_BASE: http://amundsensearch:5001
          METADATASERVICE_BASE: http://amundsenmetadata:5002
        context: .
        dockerfile: Dockerfile.frontend.local
      container_name: amundsenfrontend
      depends_on:
        - amundsenmetadata
        - amundsensearch
      ports:
        - 5000:5000
      networks:
        - amundsennet
      environment:
        - SEARCHSERVICE_BASE=http://amundsensearch:5001
        - METADATASERVICE_BASE=http://amundsenmetadata:5002
        - FRONTEND_SVC_CONFIG_MODULE_CLASS=amundsen_application.config.TestConfig
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql
    volumes:
      - mssqlvol:/var/opt/mssql
      - ./setup.sql:/usr/config/setup.sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MSSQLp@ss
      - MSSQL_PID=Developer
      - MSSQL_DB=sampledb
      - MSSQL_USER=SA
      - MSSQL_PASSWORD=MSSQLp@ss
      - MSSQL_DB_AUDIT_LOG-sample_audit_log
    ports:
      - 1433:1433



networks:
  amundsennet:
volumes:
  mssqlvol:
